### ISSUE TITLE
zsh theming

### ISSUE THREAD

**Issue by ukazap** [HackerQacker/dotfiles#1]
Hi, does this work? can you specify the theme to choose? eg. `ZSH_THEME=agnoster` 

https://github.com/OmerYe/dotfiles/blob/fc0917be5c053ea7429f227fbfb0ea39c26a51d9/.zsh_plugins.txt#L5

**Comment by HackerQacker** [comment]
Yes it works :)
But I use it for its appearance functionalities. Nothing related to ZSH_THEME
